version: "3.8"
services:
  app:
    build: . # Diretório onde está o Dockerfile
    ports:
      - "3030:3030" # Mapeamento de portas (externa:interna)
    volumes:
      - .:/app # Sincroniza os arquivos locais com o container
    environment:
      - NODE_ENV=production
